# Creando y Explorando Matrices con NumPy
>**Objetivo**
Familiarizarse con la creación de matrices en Python usando la librería NumPy.

### Instrucciones
Escribe el código para definir las siguientes cinco matrices en Python:

- Matriz identidad de
3
×
3

- Matriz nula de
4
×
4

- Matriz diagonal con los valores [2, 4, 6, 8] en la diagonal.
- Matriz de
3
×
3
con números enteros entre 1 y 10.
- Matriz transpuesta de una matriz
𝐴
A dada.

### Ejercicio

In [ ]:
import numpy as np

# 1. Matriz identidad 3x3
I = np.eye(3)
print("Matriz Identidad:\n", I)




Matriz Identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 1. Matriz identidad 4x4
I

### Ejercicio

In [2]:
# 2. Matriz nula 4x4
Z = np.zeros((4,4))
print("\nMatriz Nula:\n", Z)




Matriz Nula:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 2. Matriz nula 6x6


### Ejercicio


In [3]:
# 3. Matriz diagonal con valores específicos
D = np.diag([2, 4, 6, 8])
print("\nMatriz Diagonal:\n", D)




Matriz Diagonal:
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]


In [ ]:
# crea una matriz diagonal

### Ejercicio


In [4]:
# 4. Matriz aleatoria 3x3 con números del 1 al 10
R = np.random.randint(1, 11, (3,3))
print("\nMatriz Aleatoria:\n", R)



Matriz Aleatoria:
 [[ 1  4  4]
 [ 2  7 10]
 [ 6  7  6]]


In [ ]:
# crea una matriz con valores aleatorios

### Ejercicio


In [5]:

# 5. Matriz transpuesta de una matriz A dada
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A_T = A.T
print("\nMatriz Transpuesta:\n", A_T)


Matriz Transpuesta:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
A

In [ ]:
A_T

In [7]:
# crear una Matriz nxn y crea su traspuesta
A = np.array([[2, 3],
              [5, 7]])
print(A)

[[2 3]
 [5 7]]
